# Change these first
owner: hpware
repo: upptime # The name of this repository

sites:
  - name: SG_VULTR_1
    url: https://sg-vps.ip.yhw.tw/uptime
  - name: TW_SERVER_1
    url: https://tw-54.ip.yhw.tw/uptime
  - name: TW_SERVER_2
    url: https://tw-dynamic-1.yhw.tw/uptime
  - name: TW_SERVER_3
    url: https://tw-dynamic-2.yhw.tw/uptime

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yuanhau.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: yhw.tw Statuss
  introTitle: "status.yhw.tw"
  introMessage: 
  navbar:
    - title: Threads
      href: https://threads.net/@yhw_tw

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
